// Package telemetry is the single source of truth for the in-cluster telemetry UIs the wandb operator
// deploys when installed with --observability-mode=full (Grafana + Victoria stack) or forward (Victoria).
package telemetry

import (
	"context"
	"fmt"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/client-go/kubernetes"
)

// UI describes one viewable telemetry service.
type UI struct {
	Name     string
	Service  string
	Port     int
	URLPath  string
	ModeHint string // observability mode(s) that deploy this UI
}

// Catalog is the set of telemetry UIs `wsm telemetry` can open. Service names are generated by the
// victoria-metrics-operator (vmsingle-/vmagent-/vlsingle-<name>) and grafana-operator (<name>-service);
// verified against operator telemetry subcharts victoria-metrics-operator-0.58.1 / grafana-operator-5.21.4.
// Re-verify the naming convention on a subchart major bump.
var Catalog = []UI{
	{Name: "grafana", Service: "grafana-service", Port: 3000, URLPath: "", ModeHint: "full"},
	{Name: "victoria", Service: "vmsingle-victoria-instance", Port: 8428, URLPath: "/vmui/", ModeHint: "full or forward"},
	{Name: "logs", Service: "vlsingle-victoria-logs", Port: 9428, URLPath: "/select/vmui/", ModeHint: "full or forward"},
	{Name: "vmagent", Service: "vmagent-victoria-agent", Port: 8429, URLPath: "/", ModeHint: "full or forward"},
}

// Lookup returns the catalog entry with the given name.
func Lookup(name string) (UI, bool) {
	for _, ui := range Catalog {
		if ui.Name == name {
			return ui, true
		}
	}
	return UI{}, false
}

// ResolveService confirms ui's well-known Service exists in namespace and returns its name. The Victoria
// stack and grafana services are named deterministically by their operators (see Catalog), so a plain
// get-by-name is the reliable lookup; if the operator ever renames one, pass --service explicitly.
func ResolveService(ctx context.Context, cs *kubernetes.Clientset, namespace string, ui UI) (string, error) {
	if _, err := cs.CoreV1().Services(namespace).Get(ctx, ui.Service, metav1.GetOptions{}); err != nil {
		return "", fmt.Errorf("telemetry service %q not found in namespace %q (is the operator installed with --observability-mode=%s?); pass --service to override: %w", ui.Service, namespace, ui.ModeHint, err)
	}
	return ui.Service, nil
}
