name: "Run Checks"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  setup:
    name: Setup Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - name: Setup Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version: "1.26"
          cache: true
          cache-dependency-path: go.sum
      - name: Install dependencies
        run: go get ./...
      - name: Verify modules
        run: go mod verify

  build:
    name: Build
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - name: Setup Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version: "1.26"
          cache: true
          cache-dependency-path: go.sum
      - name: Build
        run: make build

  lint:
    name: Lint
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - name: Setup Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version: "1.26"
          cache: true
          cache-dependency-path: go.sum
      - name: Install gpgme dependencies
        run: sudo apt-get update && sudo apt-get install -y libgpgme-dev
      - name: golangci-lint
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8
        with:
          version: v2.11.4
          args: --timeout=5m

  fmt:
    name: Format
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - name: Setup Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version: "1.26"
          cache: true
          cache-dependency-path: go.sum
      - name: Format
        run: |
          make fmt
          git diff --exit-code

  dependency-check:
    name: Dependency Check
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - name: Setup Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version: "1.26"
      - name: Check for changes in go.mod or go.sum
        run: |
          go mod tidy
          git diff --exit-code go.mod go.sum
